### PR TITLE
submit a test claim for verification

### PR DESCRIPTION
**Pull request by ivarprudnikov**

### CODE REVIEW

**Comment by ivarprudnikov** [comment]
@OR13 I was following the main readme to create a PR, is there any chance you could approve?

**Comment by OR13** [comment]
Thanks! lets see if it worked properly! lol.

**Comment by OR13** [comment]
You PR does not use a JWT, this demo only supports JWTs at this time.

**Comment by OR13** [comment]
try doing this: 

https://api.did.actor/issue

Screen Shot 2022-08-09 at 11 20 38 AM

Then make the claim file look like the example:

https://github.com/OR13/endor/blob/main/docs/inbox/example.json

if my instructions are wrong, feel free to open issues and ping me.

**Comment by ivarprudnikov** [comment]
I think the confusing part is the UI in https://api.did.actor/issue as I am not clear if it just generates an example or actually creates/saves something.

How do I go from the UI to having a JSON containing  the JWT? Is it one of the commands `npm run claim:prepare`?

More explanations in the readme would be much appreciated

**Comment by OR13** [comment]
thanks! I will update the readme.

**Comment by OR13** [comment]
I tried to update the instructions here, and include an example I built following them: https://github.com/OR13/endor/pull/9

feel free to CR that PR if you think its not clear enough

**Pull request merged**
